SAMPLE_PARSED_CONFIG = {'hosts': [{'address': 'example.com', 'name': 'example', 'user': 'ghobadimhd'},
                {'address': '192.168.1.15', 'name': 'netbook', 'user': 'mamad'}],
          'recursive': True,
          'syncs': [{'hosts': [{'name': 'netbook', 'user': 'netbook'},
                               {'name': 'example', 'paths': ['/home', '/var/projects']}],
                     'name': 'default',
                     'paths': ['/home/ghobadimhd',
                               '~/projects/',
                               '/var/cache/apt-cacher-ng/'],
                     'tags': ['-v']}],
          'tags': ['-v', '--perms']}

SAMPLE_VALID_CONFIG = {'hosts': [{'address': 'example.com',
                                   'name': 'example',
                                   'user': 'ghobadimhd'},
                                  {'address': '192.168.1.15',
                                   'name': 'netbook',
                                   'user': 'mamad'}],
                        'recursive': True,
                        'syncs': [{'hosts': [{'name': 'netbook',
                                              'user': 'netbook',
                                              'address': '192.168.1.15',
                                              'paths': ['/home/ghobadimhd',
                                                        '~/projects/',
                                                        '/var/cache/apt-cacher-ng/'], },
                                             {'name': 'example',
                                              'address': 'example.com',
                                              'user':'ghobadimhd',
                                              'paths': ['/home',
                                                        '/var/projects/',
                                                        '/var/cache/apt-cacher-ng/']}],
                                   'name': 'default',
                                   'paths': ['/home/ghobadimhd',
                                             '~/projects/',
                                             '/var/cache/apt-cacher-ng/'],
                                   'tags': ['-v'], 'recursive': True}],
                        'tags': ['-v', '--perms']}
