SAMPLE_PARSED_CONFIG = {'hosts': [{'address': 'example.com', 'name': 'example', 'user': 'ghobadimhd'},
                {'address': '192.168.1.15', 'name': 'netbook', 'user': 'mamad'}],
          'recursive': True,
          'syncs': [{'hosts': [{'name': 'netbook', 'user': 'netbook'},
                               {'name': 'example', 'paths': ['/home', '/var/projects']}],
                     'name': 'default',
                     'paths': ['/home/ghobadimhd',
                               '~/projects/',
                               '/var/cache/apt-cacher-ng/'],
                     'tags': ['-v']}],
          'tags': ['-v', '--perms']}